name: Automatic updater
on: 
  push:
    branches:
      - dev

jobs:
  run:
    name: Update main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - run: |
          ls
          cd develop
          git fetch
          git checkout dev
          cd ..
          ls
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push