name: Automatic updater
on: 
  push:
    branches:
      - dev

jobs:
  run:
    name: Update main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main


      - name: Update main
        run: |
          cd develop
          git fetch
          git checkout dev
          cd ..
          ls -lh
          git status

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          author_name: LiamBindle
          author_email: liam.bindle@gmail.com
          message: 'Updated develop catalogs (automatic)'
          add: 'develop'